### ISSUE TITLE
dataset file

### ISSUE THREAD

**Issue by gopichand7202** [LaurentVeyssier/Credit-Card-fraud-detection-using-Machine-Learning#2]
I am working on this project so if you please send dataset file means it will be very helpful to my project.

**Comment by LaurentVeyssier** [comment]
the zip files are included in the repo

**Comment by gopichand7202** [comment]
The dataset file is not included in the zip file.will you please send the
zip file with dataset file

**Comment by LaurentVeyssier** [comment]
Hi, did you just try to look at the spanned zip file before asking twice?? this is the dataset man...Please take a moment and I am sure you will manage to extract.
![image](https://user-images.githubusercontent.com/68251051/210159228-6e1e8e25-5ebf-4ea9-af75-8d03a5b13a4e.png)
